spring.application.name=demo1

#paymentgateway.type=paytm
#paymentgateway.retry-count=4

paymentproperty.type=PhonePe
paymentproperty.retry-count=4
paymentproperty.isEnabled=true
paymentproperty.timeout=20
